version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html
    overwrite: true

hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/reload_nginx.sh
      timeout: 300
      runas: root
